# apiVersion: v1
# kind: Namespace
# metadata:
#   name: rbac
# ---
# # ---
# # apiVersion: rbac.authorization.k8s.io/v1
# # kind: Role
# # metadata:
# #   namespace: flask
# #   name: flask
# # rules:
# # - apiGroups: [""] # "" indicates the core API group
# #   resources: ["pods"]
# #   verbs: ["get", "watch", "list"]
# # ---
# # apiVersion: apps/v1
# # kind: Deployment
# # metadata:
# #   name: flask
# # spec:
# #   replicas: 5
# #   template:
# #     metadata:
# #       labels:
# #         app: flask
# #     spec:
# #       containers:
# #         image: sachinshakya507/hellonode:1.0.4
# # apiVersion: apps/v1
# # kind: Deployment
# # metadata:
# #   name: flask
# #   namespace: flask
# # spec:
# #   replicas: 2
# #   template:
# #     metadata:
# #       labels:
# #         app: flask
# #     spec:
# #       serviceAccount: flask-backend
# #       containers:
# #       - image: sachinshakya507/hellonode:1.0.4
# #         name: flask
# #         ports:
# #         - containerPort: 3000
# kind: Role
# apiVersion: rbac.authorization.k8s.io/v1
# metadata:
#   name: flask-backend-role
#   namespace: rbac
# rules:
#   - apiGroups: [""]
#     resources: ["pods"]
#     verbs: ["get", "list", "watch"]
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# # This role binding allows "jane" to read pods in the "default" namespace.
# # You need to already have a Role named "pod-reader" in that namespace.
# kind: RoleBinding
# metadata:
#   name: flask-backend-rolebinding
#   namespace: rbac
# subjects:
# # You can specify more than one "subject"
# - kind: User
#   name: john # "name" is case sensitive
#   apiGroup: rbac.authorization.k8s.io
# roleRef:
#   # "roleRef" specifies the binding to a Role / ClusterRole
#   kind: Role #this must be Role or ClusterRole
#   name: flask-backend-role # this must match the name of the Role or ClusterRole you wish to bind to
#   apiGroup: rbac.authorization.k8s.io
# ---
apiVersion: v1
kind: Namespace
metadata:
  name: flask
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flask-backend
  namespace: flask
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flask-backend-role
  namespace: flask
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flask-backend-role-binding
  namespace: flask
subjects:
  - kind: ServiceAccount
    name: flask-backend
    namespace: flask
roleRef:
  kind: Role
  name: flask-backend-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  namespace: flask
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 2 
  template:
    metadata:
      labels:
        app: flask
    spec:
      serviceAccount: flask-backend
      containers:
      - name: flask
        image: sachinshakya507/hellonode:1.0.4
        ports:
        - containerPort: 3000